spring:
  datasource:
    url: jdbc:mysql://phoenix-database.clemtdx79oxt.ap-northeast-2.rds.amazonaws.com:3306/kkanbustock
    username: admin
    password: phoenix123

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false #osiv
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true

logging:
  level:
    org.springframework.orm.jpa: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.transaction: DEBUG

